// <auto-generated />
using System;
using ConfigLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfigLibrary.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20250418160415_SeedSampleMig")]
    partial class SeedSampleMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConfigLibrary.Models.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ApplicationName = "SERVICE-A",
                            IsActive = true,
                            LastModified = new DateTime(2025, 4, 18, 19, 4, 15, 365, DateTimeKind.Local).AddTicks(6906),
                            Name = "SiteName",
                            Type = "string",
                            Value = "soty.io"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ApplicationName = "SERVICE-B",
                            IsActive = true,
                            LastModified = new DateTime(2025, 4, 18, 19, 4, 15, 365, DateTimeKind.Local).AddTicks(7106),
                            Name = "IsBasketEnabled",
                            Type = "bool",
                            Value = "1"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ApplicationName = "SERVICE-A",
                            IsActive = false,
                            LastModified = new DateTime(2025, 4, 18, 19, 4, 15, 365, DateTimeKind.Local).AddTicks(7114),
                            Name = "MaxItemCount",
                            Type = "int",
                            Value = "50"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
